#!/usr/bin/env python3

import itertools
from collections import Counter, defaultdict

from separating_words.canonical_generator import generate_canonical_dfas

U = "10101010101010101010101010101101010101001010101"
V = "10101101010101001010101010101010101010101010101"


def run(t, word):
    q = 0
    for b in word:
        q = t[q][int(b)]
    return q


def conjugate(t, p):
    """
    Relabel states by p:
        T'_a = p o T_a o p^{-1}
    """
    n = len(t)
    pinv = [0] * n

    for old, new in enumerate(p):
        pinv[new] = old

    out = []

    for new_q in range(n):
        old_q = pinv[new_q]
        out.append(
            (
                p[t[old_q][0]],
                p[t[old_q][1]],
            )
        )

    return tuple(out)


def canonical_conjugacy(t):
    return min(
        conjugate(t, p)
        for p in itertools.permutations(range(len(t)))
    )


def permutation_cycle_type(mapping):
    n = len(mapping)
    seen = [False] * n
    cycles = []

    for q in range(n):
        if seen[q]:
            continue

        cur = q
        length = 0

        while not seen[cur]:
            seen[cur] = True
            length += 1
            cur = mapping[cur]

        cycles.append(length)

    return tuple(sorted(cycles))


def compose(f, g):
    # f o g
    return tuple(f[g[i]] for i in range(len(f)))


def transformation_semigroup(t):
    """
    Exact semigroup generated by T0 and T1.
    For 5 states there are at most 5^5 = 3125 maps.
    """
    n = len(t)

    t0 = tuple(row[0] for row in t)
    t1 = tuple(row[1] for row in t)

    known = {t0, t1}
    frontier = [t0, t1]

    while frontier:
        f = frontier.pop()

        # Multiplication on both sides by generators.
        for g in (t0, t1):
            for h in (compose(f, g), compose(g, f)):
                if h not in known:
                    known.add(h)
                    frontier.append(h)

    rank_counts = Counter(
        len(set(f)) for f in known
    )

    return len(known), tuple(sorted(rank_counts.items()))


def main():
    witnesses = []

    global_idx = 0

    for k in range(1, 6):
        for t in generate_canonical_dfas(k):

            if run(t, U) != run(t, V):
                witnesses.append((global_idx, k, tuple(t)))

            global_idx += 1

    if global_idx != 166_152:
        raise RuntimeError(
            f"expected 166152 automata, got {global_idx}"
        )

    if len(witnesses) != 52:
        raise RuntimeError(
            f"expected 52 witnesses, got {len(witnesses)}"
        )

    if any(k != 5 for _, k, _ in witnesses):
        raise RuntimeError("found non-5-state witness")

    print("===== V5.3 EXACT CONJUGACY ANALYSIS =====")
    print("witnesses:", len(witnesses))
    print()

    conjugacy = defaultdict(list)

    for idx, _, t in witnesses:
        conjugacy[canonical_conjugacy(t)].append((idx, t))

    print("EXACT CONJUGACY CLASSES:", len(conjugacy))
    print("class sizes:",
          sorted((len(v) for v in conjugacy.values()), reverse=True))
    print()

    cycle_counter = Counter()
    semigroup_counter = Counter()

    rows = []

    for rank, (canon, members) in enumerate(
        sorted(
            conjugacy.items(),
            key=lambda x: (-len(x[1]), x[0])
        ),
        1,
    ):
        t0 = tuple(row[0] for row in canon)
        t1 = tuple(row[1] for row in canon)

        cycle_type = permutation_cycle_type(t1)
        semigroup_size, rank_profile = transformation_semigroup(canon)

        cycle_counter[cycle_type] += len(members)
        semigroup_counter[
            (semigroup_size, rank_profile)
        ] += len(members)

        rows.append(
            (
                rank,
                len(members),
                cycle_type,
                semigroup_size,
                rank_profile,
                [x[0] for x in members],
                canon,
            )
        )

    print("===== T1 CYCLE TYPES =====")
    for cycle_type, n in cycle_counter.most_common():
        print(f"{cycle_type}: {n}")

    print()
    print("===== SEMIGROUP TYPES =====")
    print("distinct semigroup profiles:",
          len(semigroup_counter))

    for (size, profile), n in semigroup_counter.most_common():
        print(
            f"witnesses={n:>2} "
            f"| semigroup_size={size:>4} "
            f"| rank_profile={profile}"
        )

    print()
    print("===== CONJUGACY CLASSES =====")

    for (
        rank,
        n,
        cycle_type,
        sg_size,
        rank_profile,
        indices,
        canon,
    ) in rows:

        print()
        print(f"CLASS {rank}: {n} witnesses")
        print(" indices:", indices)
        print(" T1 cycle type:", cycle_type)
        print(" semigroup size:", sg_size)
        print(" rank profile:", rank_profile)
        print(" canonical T:", canon)

    print()
    print("===== SUMMARY =====")
    print("witnesses =", len(witnesses))
    print("exact conjugacy classes =", len(conjugacy))
    print(
        "distinct T1 cycle types =",
        len(cycle_counter),
    )
    print(
        "distinct semigroup profiles =",
        len(semigroup_counter),
    )


if __name__ == "__main__":
    main()
